# -*- coding: utf-8 -*-
"""
Generates data/rules/urban_plan_id_registry.json -- the canonical, stable
plan_id registry for every record in data/sources/gis/新北市都市計畫範圍_
名稱對照表.json (the manual key/sdf_id -> official-name fix-up table; see
docs/source_inventory.md's `ntpc_plan_boundary_name_lookup_patch` entry).

Why a separate registry instead of using the Chinese plan_name directly as
the runtime key: `engine/land_use_ratio_engine.py`'s per-plan floor-area-
ratio table (data/rules/plan_zone_floor_area_ratios.json) already keys its
one existing entry on the internal slug "jinshan", not the Chinese string
"金山都市計畫" -- this registry must produce that SAME "jinshan" value for
that plan, or every existing Golden-Case-verified Layer 2 lookup silently
breaks. For every other plan (no existing curated slug), this script
derives a deterministic id from the shapefile's own `key`/`SDF_ID`
attribute pair (verified intact at the source, unlike Name/LblName) --
never a hash of the display name, and never the display name itself, per
this round's explicit "plan_id must be stable/testable/version-controlled,
not a display-name-derived guess" instruction.

Rerunning this script is idempotent: given the same source lookup table
and the same CURATED_PLAN_IDS below, it produces byte-identical output.
"""
from __future__ import annotations

import json
import os
import sys

THIS_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(THIS_DIR)

SOURCE_LOOKUP_PATH = os.path.join(REPO_ROOT, "data", "sources", "gis", "新北市都市計畫範圍_名稱對照表.json")
OUTPUT_PATH = os.path.join(REPO_ROOT, "data", "rules", "urban_plan_id_registry.json")

# The one plan_id already curated (and Golden-Case-verified) in
# data/rules/plan_zone_floor_area_ratios.json -- this script must reproduce
# it exactly, keyed by the SAME (source_key, source_sdf_id) pair the name-
# lookup patch uses for 金山都市計畫 (key=64, sdf_id=28; see docs/
# source_inventory.md). Adding a curated id for another plan later is a
# one-line addition here, never an automatic/guessed derivation.
CURATED_PLAN_IDS = {
    ("64", 28): "jinshan",
}

# The lookup table's own sentinel for "not inside any formal 都市計畫" (see
# scripts/sync_ntpc_zoning_dataset.py's NON_PLAN_SENTINEL) -- these records
# get plan_id=null and is_urban_plan=false, never a synthetic plan_id.
NON_PLAN_SENTINEL = "非都市計畫區"


def build_registry(source_lookup_path: str = SOURCE_LOOKUP_PATH) -> dict:
    with open(source_lookup_path, "r", encoding="utf-8") as f:
        source = json.load(f)

    entries = []
    seen_plan_ids = {}
    for row in source["lookup"]:
        key = str(row["key"])
        sdf_id = int(row["sdf_id"])
        name = row["name"]
        is_urban_plan = name != NON_PLAN_SENTINEL

        if not is_urban_plan:
            plan_id = None
        elif (key, sdf_id) in CURATED_PLAN_IDS:
            plan_id = CURATED_PLAN_IDS[(key, sdf_id)]
        else:
            # Deterministic, stable, and testable: derived from the
            # shapefile's own verified-intact key/SDF_ID attributes, never
            # from the (corrupted-at-source, display-only) plan name.
            plan_id = f"ntpc_plan_{key}_{sdf_id}"

        if plan_id is not None:
            if plan_id in seen_plan_ids:
                raise ValueError(
                    f"plan_id衝突：{plan_id!r}同時對應(key={key}, sdf_id={sdf_id})與"
                    f"{seen_plan_ids[plan_id]!r}，registry產生邏輯有誤，不可靜默覆蓋"
                )
            seen_plan_ids[plan_id] = (key, sdf_id)

        entries.append({
            "source_key": key,
            "source_sdf_id": sdf_id,
            "plan_id": plan_id,
            "plan_name": name,
            "is_urban_plan": is_urban_plan,
        })

    return {
        "_meta": {
            "purpose": (
                "Canonical, stable plan_id for every record in "
                "新北市都市計畫範圍_名稱對照表.json, generated by "
                "scripts/build_urban_plan_id_registry.py -- see that "
                "script's module docstring for why plan_id is never a hash "
                "or the display name itself."
            ),
            "generated_from": os.path.relpath(source_lookup_path, REPO_ROOT).replace("\\", "/"),
            "curated_plan_ids": {f"{k[0]}/{k[1]}": v for k, v in CURATED_PLAN_IDS.items()},
            "non_plan_sentinel": NON_PLAN_SENTINEL,
        },
        "entries": entries,
    }


def main() -> int:
    registry = build_registry()
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(registry, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"已產生 {len(registry['entries'])} 筆記錄至 {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
